language: python
python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install flake8

script:
  - flake8 . --count --ignore=E501 --exclude="cogs/help.py" --exclude="cogs/animotes/animotes.py"
  # Excluding help.py since i didnt write it
